### ISSUE TITLE
[ ✅ TASK ] 사용자 인증 화면 구현

### ISSUE THREAD

**Issue by 2-phones** [SemiPerm/frontend#9]
## Description
- Type : FEAT
- About : SNS 로그인 화면 구현 (첫 가입시 동의 모달과 추가 정보 수집 화면 제공) 각 플랫폼 accessToken 받아와 서버에 넘기는 방식
## Todo
- [ ] 화면 UI 구현
- [ ] 비즈니스 로직 (토큰 방식) 구현
- [ ] 서버 DB 연동
